// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is one row in the live transport console.
 */
export class Entry {
    "id": number;
    "timestamp": string;
    "transport": string;
    "direction": string;
    "target"?: string;
    "summary": string;
    "detail"?: string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("transport" in $$source)) {
            this["transport"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}
