// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DMXLiveStatus describes the USB DMX streaming session for the UI.
 */
export class DMXLiveStatus {
    "connected": boolean;
    "error"?: string;
    "devicePath"?: string;
    "deviceName"?: string;
    "fixtureId"?: string;

    /** Creates a new DMXLiveStatus instance. */
    constructor($$source: Partial<DMXLiveStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXLiveStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXLiveStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DMXLiveStatus($$parsedSource as Partial<DMXLiveStatus>);
    }
}

/**
 * DMXOutputUpdate sets one DMX slot (address 1-512) to a value 0-255.
 */
export class DMXOutputUpdate {
    "universeId"?: string;
    "address": number;
    "value": number;

    /** Creates a new DMXOutputUpdate instance. */
    constructor($$source: Partial<DMXOutputUpdate> = {}) {
        if (!("address" in $$source)) {
            this["address"] = 0;
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXOutputUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXOutputUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DMXOutputUpdate($$parsedSource as Partial<DMXOutputUpdate>);
    }
}
