// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UIConfig holds UI theming configuration for the update progress window.
 */
export class UIConfig {
    /**
     * Title is the window title for the update dialog.
     * Defaults to "Update Available".
     */
    "Title": string;

    /**
     * IconPath is the path to a custom icon for the update dialog.
     */
    "IconPath": string;

    /**
     * BackgroundColor is the background color in hex format (e.g., "#ffffff").
     */
    "BackgroundColor": string;

    /**
     * TextColor is the text color in hex format (e.g., "#000000").
     */
    "TextColor": string;

    /**
     * AccentColor is the accent/progress bar color in hex format (e.g., "#007bff").
     */
    "AccentColor": string;

    /**
     * ProgressBarColor is the progress bar fill color in hex format.
     * Defaults to AccentColor if not set.
     */
    "ProgressBarColor": string;

    /**
     * ButtonColor is the button background color in hex format.
     */
    "ButtonColor": string;

    /**
     * ButtonTextColor is the button text color in hex format.
     */
    "ButtonTextColor": string;

    /** Creates a new UIConfig instance. */
    constructor($$source: Partial<UIConfig> = {}) {
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("IconPath" in $$source)) {
            this["IconPath"] = "";
        }
        if (!("BackgroundColor" in $$source)) {
            this["BackgroundColor"] = "";
        }
        if (!("TextColor" in $$source)) {
            this["TextColor"] = "";
        }
        if (!("AccentColor" in $$source)) {
            this["AccentColor"] = "";
        }
        if (!("ProgressBarColor" in $$source)) {
            this["ProgressBarColor"] = "";
        }
        if (!("ButtonColor" in $$source)) {
            this["ButtonColor"] = "";
        }
        if (!("ButtonTextColor" in $$source)) {
            this["ButtonTextColor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): UIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIConfig($$parsedSource as Partial<UIConfig>);
    }
}

/**
 * UpdateInfo contains information about an available update.
 */
export class UpdateInfo {
    /**
     * UpdateAvailable is true if an update is available.
     */
    "updateAvailable": boolean;

    /**
     * CurrentVersion is the current version of the application.
     */
    "currentVersion": string;

    /**
     * LatestVersion is the latest available version.
     */
    "latestVersion": string;

    /**
     * ReleaseNotes contains the release notes/changelog for the update.
     */
    "releaseNotes": string;

    /**
     * ReleaseURL is a link to the release page.
     */
    "releaseUrl": string;

    /**
     * PublishedAt is the publication date of the release.
     */
    "publishedAt": string;

    /**
     * AssetName is the name of the asset that will be downloaded.
     */
    "assetName": string;

    /**
     * AssetURL is the direct download URL for the asset.
     */
    "assetUrl": string;

    /**
     * AssetSize is the size of the asset in bytes.
     */
    "assetSize": number;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("updateAvailable" in $$source)) {
            this["updateAvailable"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("assetUrl" in $$source)) {
            this["assetUrl"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
