// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides self-update functionality for Wails applications.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CanUpdate returns true if the current process has permission to update itself.
 * This checks if the executable is writable.
 */
export function CanUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(2953453236);
}

/**
 * Check checks if an update is available.
 * Returns UpdateInfo with details about the available update.
 * This is the recommended first step in the update flow.
 */
export function Check(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(4071971591).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckForUpdate is an alias for Check for backwards compatibility.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3752438091).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadAndInstall downloads and installs the pending update in one step.
 * You must call Check first to detect an available update.
 * Returns true if the update was successful.
 * The application should be restarted after a successful update.
 */
export function DownloadAndInstall(): $CancellablePromise<boolean> {
    return $Call.ByID(3722796977);
}

/**
 * GetCurrentVersion returns the current application version.
 */
export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(3324825396);
}

/**
 * GetLatestRelease returns information about the latest release.
 * This is similar to Check but doesn't store the pending update.
 */
export function GetLatestRelease(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3881423865).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPlatformInfo returns information about the current platform.
 * This can be useful for debugging update issues or for determining
 * which asset to expect.
 */
export function GetPlatformInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1885599284).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetUIConfig returns the UI configuration for theming the update dialog.
 * Returns nil if no UI configuration is set.
 */
export function GetUIConfig(): $CancellablePromise<$models.UIConfig | null> {
    return $Call.ByID(3680422543).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * PerformUpdate is an alias for DownloadAndInstall for backwards compatibility.
 */
export function PerformUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(1383834363);
}

/**
 * Restart restarts the application after an update.
 * This is a convenience method that can be called after DownloadAndInstall.
 * Note: This method may not return if the restart is successful.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2688925868);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.UIConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
