// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * LicenseInfo is the license state exposed to the UI and controller.
 */
export class LicenseInfo {
    "edition": string;
    "status": string;
    "expiresAt"?: time$0.Time | null;
    "customerName"?: string;
    "customerId"?: string;
    "daysRemaining": number;
    "machineId": string;
    "features": { [_ in string]?: boolean };

    /** Creates a new LicenseInfo instance. */
    constructor($$source: Partial<LicenseInfo> = {}) {
        if (!("edition" in $$source)) {
            this["edition"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("daysRemaining" in $$source)) {
            this["daysRemaining"] = 0;
        }
        if (!("machineId" in $$source)) {
            this["machineId"] = "";
        }
        if (!("features" in $$source)) {
            this["features"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LicenseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LicenseInfo {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField7_0($$parsedSource["features"]);
        }
        return new LicenseInfo($$parsedSource as Partial<LicenseInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
