// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as console$0 from "../console/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as controller$0 from "../controller/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dmx$0 from "../dmx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serial$0 from "../serial/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddWLEDDevice(input: controller$0.AddWLEDDeviceInput): $CancellablePromise<controller$0.WLEDDevice> {
    return $Call.ByID(323424369, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1117350835);
}

export function ApplyDMXLivePatch(updates: dmx$0.DMXOutputUpdate[]): $CancellablePromise<void> {
    return $Call.ByID(2042273641, updates);
}

export function ApplyLightingScene(id: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2886030666, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ApplyNetworkSettings(): $CancellablePromise<controller$0.NetworkApplyResult> {
    return $Call.ByID(3615869373).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ApplyWLEDDevicePreset(deviceID: string, presetID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(190781825, deviceID, presetID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckForUpdates runs the platform updater flow (download dialog, install prompt, etc.).
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(3484413137);
}

/**
 * ClearConsoleEntries empties the live transport console buffer.
 */
export function ClearConsoleEntries(): $CancellablePromise<void> {
    return $Call.ByID(1300755656);
}

/**
 * CloseDetachedConsoleWindow closes the detached Console window if open.
 */
export function CloseDetachedConsoleWindow(): $CancellablePromise<void> {
    return $Call.ByID(2955751393);
}

export function ControllerSummary(): $CancellablePromise<string> {
    return $Call.ByID(3899562766);
}

export function CreateDMXFixture(input: controller$0.UpsertDMXFixtureInput): $CancellablePromise<controller$0.DMXFixture> {
    return $Call.ByID(2997071716, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CreateLightingScene(input: controller$0.UpsertLightingSceneInput): $CancellablePromise<controller$0.LightingScene> {
    return $Call.ByID(3891090286, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CreateWLEDDevicePreset(deviceID: string, name: string): $CancellablePromise<controller$0.WLEDDevicePreset> {
    return $Call.ByID(177225157, deviceID, name).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DMXEmergencyStop(): $CancellablePromise<void> {
    return $Call.ByID(3841795376);
}

export function DefaultControllerSettings(): $CancellablePromise<controller$0.ControllerSettings> {
    return $Call.ByID(2351146182).then(($result: any) => {
        return $$createType6($result);
    });
}

export function DeleteDMXFixture(id: string): $CancellablePromise<void> {
    return $Call.ByID(2715504683, id);
}

export function DeleteLightingScene(id: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2741944951, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteWLEDDevicePreset(deviceID: string, presetID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(104617118, deviceID, presetID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportConfigurationBackup prompts for a destination file and writes the full configuration bundle.
 */
export function ExportConfigurationBackup(): $CancellablePromise<string> {
    return $Call.ByID(4179458988);
}

/**
 * ExportDMXFixtureConfig prompts for a destination file and writes the provided
 * fixture configuration JSON to it. The contents are produced by the GUI layer.
 * Returns the chosen path, or ErrConfigurationBackupCancelled when dismissed.
 */
export function ExportDMXFixtureConfig(suggestedFilename: string, contents: string): $CancellablePromise<string> {
    return $Call.ByID(3174069144, suggestedFilename, contents);
}

/**
 * ExportLightingScene prompts for a destination and writes a portable scene JSON file.
 */
export function ExportLightingScene(id: string): $CancellablePromise<string> {
    return $Call.ByID(897981220, id);
}

/**
 * GetCompanionStatus returns whether the phone companion is enabled/listening and its URLs.
 */
export function GetCompanionStatus(): $CancellablePromise<$models.CompanionStatus> {
    return $Call.ByID(4265778090).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetControllerSnapshot(): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(4123599706).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetDMXFixtureLiveLayoutJSON(fixtureID: string): $CancellablePromise<string> {
    return $Call.ByID(2477334130, fixtureID);
}

export function GetDMXLiveStatus(): $CancellablePromise<dmx$0.DMXLiveStatus> {
    return $Call.ByID(1614902043).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetDMXPartyState(): $CancellablePromise<controller$0.DMXPartyState> {
    return $Call.ByID(360607294).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetDMXState(): $CancellablePromise<controller$0.DMXState> {
    return $Call.ByID(2859174524).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetDeviceDetail(deviceID: string): $CancellablePromise<controller$0.WLEDDeviceDetail> {
    return $Call.ByID(664315657, deviceID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetIgnoredDevices(): $CancellablePromise<controller$0.WLEDDevice[]> {
    return $Call.ByID(3651794263).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ImportConfigurationBackup prompts for a backup file and restores all persisted configuration.
 */
export function ImportConfigurationBackup(): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2680155405).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportLightingScene prompts for a portable scene file and creates it locally.
 */
export function ImportLightingScene(): $CancellablePromise<controller$0.LightingScene> {
    return $Call.ByID(2874775773).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * IsConsoleWindowDetached reports whether the detached Console window is open.
 */
export function IsConsoleWindowDetached(): $CancellablePromise<boolean> {
    return $Call.ByID(4287288425);
}

/**
 * ListConsoleEntries returns transport console entries with ID greater than
 * afterID, capped at limit. Used by the Settings → Console tab.
 */
export function ListConsoleEntries(afterID: number, limit: number): $CancellablePromise<console$0.Entry[]> {
    return $Call.ByID(3101953237, afterID, limit).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListDMXPartyAudioInputDevices(): $CancellablePromise<controller$0.DMXPartyAudioInputDevice[]> {
    return $Call.ByID(4243575882).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListUSBSerialDevices(): $CancellablePromise<controller$0.USBSerialDevice[]> {
    return $Call.ByID(147791315).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * OpenDetachedConsoleWindow opens (or focuses) the detached Console window.
 */
export function OpenDetachedConsoleWindow(): $CancellablePromise<void> {
    return $Call.ByID(698290765);
}

export function ProvisionDevice(deviceID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2270029467, deviceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RefreshDevice(deviceID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2016944831, deviceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveDevice(deviceID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(181059520, deviceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RenameDevice(deviceID: string, name: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(1141541742, deviceID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveControllerSettings(settings: controller$0.ControllerSettings): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2607228358, settings).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetCompanionStatusProvider wires the HTTP companion status reporter (called from main).
 */
export function SetCompanionStatusProvider(fn: any): $CancellablePromise<void> {
    return $Call.ByID(3615465219, fn);
}

export function SetDMXFixtureLiveLayoutJSON(fixtureID: string, layoutJSON: string): $CancellablePromise<void> {
    return $Call.ByID(3105573870, fixtureID, layoutJSON);
}

export function SetDMXPartyConfig(config: controller$0.DMXPartyConfig): $CancellablePromise<controller$0.DMXPartyState> {
    return $Call.ByID(202387099, config).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetDMXUniverseUSBDevice(universeID: string, deviceID: string): $CancellablePromise<controller$0.DMXState> {
    return $Call.ByID(3336682260, universeID, deviceID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SetDefaultLightingScene marks a scene as the startup default. Pass an empty id to clear.
 */
export function SetDefaultLightingScene(id: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2443837021, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetDeviceIgnored(deviceID: string, ignored: boolean): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(1137278958, deviceID, ignored).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetDeviceState(deviceID: string, state: { [_ in string]?: any }): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(1128645809, deviceID, state).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetGlobalState(state: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(918662134, state).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SetPartyLightingScene marks a scene as the designated party-mode scene. Pass an empty id to clear.
 */
export function SetPartyLightingScene(id: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(1174917270, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetSelectedUSBSerialDevice(deviceID: string): $CancellablePromise<controller$0.DMXState> {
    return $Call.ByID(3976246093, deviceID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function StartDMXLive(fixtureID: string): $CancellablePromise<void> {
    return $Call.ByID(2961004277, fixtureID);
}

export function StartDMXParty(): $CancellablePromise<void> {
    return $Call.ByID(4103913889);
}

/**
 * StartLightingSceneParty starts party mode using the configured party scene's targets.
 */
export function StartLightingSceneParty(): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2576441862).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopDMXLive(): $CancellablePromise<void> {
    return $Call.ByID(1211112949);
}

export function StopDMXParty(): $CancellablePromise<void> {
    return $Call.ByID(3272345249);
}

export function UpdateDMXFixture(input: controller$0.UpsertDMXFixtureInput): $CancellablePromise<controller$0.DMXFixture> {
    return $Call.ByID(1580909073, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateLightingScene(input: controller$0.UpsertLightingSceneInput): $CancellablePromise<controller$0.LightingScene> {
    return $Call.ByID(1011675105, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UpdateWLEDDevicePreset(deviceID: string, presetID: string, name: string, state: { [_ in string]?: any }): $CancellablePromise<controller$0.WLEDDevicePreset> {
    return $Call.ByID(3760929624, deviceID, presetID, name, state).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdatesSupported reports whether the built-in application updater is available.
 */
export function UpdatesSupported(): $CancellablePromise<boolean> {
    return $Call.ByID(1737136614);
}

// Private type creation functions
const $$createType0 = controller$0.WLEDDevice.createFrom;
const $$createType1 = controller$0.ControllerSnapshot.createFrom;
const $$createType2 = controller$0.NetworkApplyResult.createFrom;
const $$createType3 = controller$0.DMXFixture.createFrom;
const $$createType4 = controller$0.LightingScene.createFrom;
const $$createType5 = controller$0.WLEDDevicePreset.createFrom;
const $$createType6 = controller$0.ControllerSettings.createFrom;
const $$createType7 = $models.CompanionStatus.createFrom;
const $$createType8 = dmx$0.DMXLiveStatus.createFrom;
const $$createType9 = controller$0.DMXPartyState.createFrom;
const $$createType10 = controller$0.DMXState.createFrom;
const $$createType11 = controller$0.WLEDDeviceDetail.createFrom;
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = console$0.Entry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = controller$0.DMXPartyAudioInputDevice.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = serial$0.USBSerialDevice.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Map($Create.Any, $Create.Any);
