// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as console$0 from "../console/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as controller$0 from "../controller/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dmx$0 from "../dmx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serial$0 from "../serial/models.js";

export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1117350835);
}

export function ApplyDMXLivePatch(updates: dmx$0.DMXOutputUpdate[]): $CancellablePromise<void> {
    return $Call.ByID(2042273641, updates);
}

export function ApplyNetworkSettings(): $CancellablePromise<controller$0.NetworkApplyResult> {
    return $Call.ByID(3615869373).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearConsoleEntries empties the live transport console buffer.
 */
export function ClearConsoleEntries(): $CancellablePromise<void> {
    return $Call.ByID(1300755656);
}

export function ControllerSummary(): $CancellablePromise<string> {
    return $Call.ByID(3899562766);
}

export function CreateDMXFixture(input: controller$0.UpsertDMXFixtureInput): $CancellablePromise<controller$0.DMXFixture> {
    return $Call.ByID(2997071716, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DefaultControllerSettings(): $CancellablePromise<controller$0.ControllerSettings> {
    return $Call.ByID(2351146182).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteDMXFixture(id: string): $CancellablePromise<void> {
    return $Call.ByID(2715504683, id);
}

export function DiscoverDevicesNow(): $CancellablePromise<controller$0.WLEDDevice[]> {
    return $Call.ByID(3302843696).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetControllerSnapshot(): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(4123599706).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetDMXLiveStatus(): $CancellablePromise<dmx$0.DMXLiveStatus> {
    return $Call.ByID(1614902043).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetDMXState(): $CancellablePromise<controller$0.DMXState> {
    return $Call.ByID(2859174524).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetDeviceDetail(deviceID: string): $CancellablePromise<controller$0.WLEDDeviceDetail> {
    return $Call.ByID(664315657, deviceID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetIgnoredDevices(): $CancellablePromise<controller$0.WLEDDevice[]> {
    return $Call.ByID(3651794263).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(1436929455, name);
}

/**
 * ListConsoleEntries returns transport console entries with ID greater than
 * afterID, capped at limit. Used by the Settings → Console tab.
 */
export function ListConsoleEntries(afterID: number, limit: number): $CancellablePromise<console$0.Entry[]> {
    return $Call.ByID(3101953237, afterID, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListUSBSerialDevices(): $CancellablePromise<controller$0.USBSerialDevice[]> {
    return $Call.ByID(147791315).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ProvisionDevice(deviceID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2270029467, deviceID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RefreshDevice(deviceID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2016944831, deviceID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RemoveDevice(deviceID: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(181059520, deviceID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RenameDevice(deviceID: string, name: string): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(1141541742, deviceID, name).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveControllerSettings(settings: controller$0.ControllerSettings): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(2607228358, settings).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetDeviceIgnored(deviceID: string, ignored: boolean): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(1137278958, deviceID, ignored).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetDeviceState(deviceID: string, state: { [_ in string]?: any }): $CancellablePromise<controller$0.ControllerSnapshot> {
    return $Call.ByID(1128645809, deviceID, state).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetGlobalState(state: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(918662134, state).then(($result: any) => {
        return $$createType13($result);
    });
}

export function SetSelectedUSBSerialDevice(deviceID: string): $CancellablePromise<controller$0.DMXState> {
    return $Call.ByID(3976246093, deviceID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function StartDMXLive(fixtureID: string): $CancellablePromise<void> {
    return $Call.ByID(2961004277, fixtureID);
}

export function StopDMXLive(): $CancellablePromise<void> {
    return $Call.ByID(1211112949);
}

export function UpdateDMXFixture(input: controller$0.UpsertDMXFixtureInput): $CancellablePromise<controller$0.DMXFixture> {
    return $Call.ByID(1580909073, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = controller$0.NetworkApplyResult.createFrom;
const $$createType1 = controller$0.DMXFixture.createFrom;
const $$createType2 = controller$0.ControllerSettings.createFrom;
const $$createType3 = controller$0.WLEDDevice.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = controller$0.ControllerSnapshot.createFrom;
const $$createType6 = dmx$0.DMXLiveStatus.createFrom;
const $$createType7 = controller$0.DMXState.createFrom;
const $$createType8 = controller$0.WLEDDeviceDetail.createFrom;
const $$createType9 = console$0.Entry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = serial$0.USBSerialDevice.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
