// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GoldbusLightService from "./goldbuslightservice.js";
export {
    GoldbusLightService
};
