// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CompanionStatus mirrors remotehttp.CompanionStatus for the Wails UI.
 */
export class CompanionStatus {
    "enabled": boolean;
    "listening": boolean;
    "port": number;
    "urls": string[];
    "qrDataUrl"?: string;

    /** Creates a new CompanionStatus instance. */
    constructor($$source: Partial<CompanionStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("listening" in $$source)) {
            this["listening"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompanionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CompanionStatus {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField3_0($$parsedSource["urls"]);
        }
        return new CompanionStatus($$parsedSource as Partial<CompanionStatus>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
