// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * USBSerialDevice describes one candidate USB serial device for DMX output selection.
 */
export class USBSerialDevice {
    "id": string;
    "path": string;
    "name": string;
    "description"?: string;

    /** Creates a new USBSerialDevice instance. */
    constructor($$source: Partial<USBSerialDevice> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new USBSerialDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): USBSerialDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new USBSerialDevice($$parsedSource as Partial<USBSerialDevice>);
    }
}
