// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class AccessPointSettings {
    "enabled": boolean;
    "connection": string;
    "interfaceName": string;
    "ssid": string;
    "password": string;
    "channel": number;

    /** Creates a new AccessPointSettings instance. */
    constructor($$source: Partial<AccessPointSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("connection" in $$source)) {
            this["connection"] = "";
        }
        if (!("interfaceName" in $$source)) {
            this["interfaceName"] = "";
        }
        if (!("ssid" in $$source)) {
            this["ssid"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessPointSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessPointSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessPointSettings($$parsedSource as Partial<AccessPointSettings>);
    }
}

export class BridgeSettings {
    "enabled": boolean;
    "apInterface": string;
    "upstreamInterface": string;

    /** Creates a new BridgeSettings instance. */
    constructor($$source: Partial<BridgeSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("apInterface" in $$source)) {
            this["apInterface"] = "";
        }
        if (!("upstreamInterface" in $$source)) {
            this["upstreamInterface"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BridgeSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): BridgeSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BridgeSettings($$parsedSource as Partial<BridgeSettings>);
    }
}

export class ControllerCapabilities {
    "nmcliAvailable": boolean;

    /** Creates a new ControllerCapabilities instance. */
    constructor($$source: Partial<ControllerCapabilities> = {}) {
        if (!("nmcliAvailable" in $$source)) {
            this["nmcliAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerCapabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ControllerCapabilities($$parsedSource as Partial<ControllerCapabilities>);
    }
}

export class ControllerSettings {
    "accessPoint": AccessPointSettings;
    "upstream": UpstreamSettings;
    "bridge": BridgeSettings;
    "discovery": DiscoverySettings;
    "provisioning": ProvisioningSettings;

    /** Creates a new ControllerSettings instance. */
    constructor($$source: Partial<ControllerSettings> = {}) {
        if (!("accessPoint" in $$source)) {
            this["accessPoint"] = (new AccessPointSettings());
        }
        if (!("upstream" in $$source)) {
            this["upstream"] = (new UpstreamSettings());
        }
        if (!("bridge" in $$source)) {
            this["bridge"] = (new BridgeSettings());
        }
        if (!("discovery" in $$source)) {
            this["discovery"] = (new DiscoverySettings());
        }
        if (!("provisioning" in $$source)) {
            this["provisioning"] = (new ProvisioningSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerSettings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accessPoint" in $$parsedSource) {
            $$parsedSource["accessPoint"] = $$createField0_0($$parsedSource["accessPoint"]);
        }
        if ("upstream" in $$parsedSource) {
            $$parsedSource["upstream"] = $$createField1_0($$parsedSource["upstream"]);
        }
        if ("bridge" in $$parsedSource) {
            $$parsedSource["bridge"] = $$createField2_0($$parsedSource["bridge"]);
        }
        if ("discovery" in $$parsedSource) {
            $$parsedSource["discovery"] = $$createField3_0($$parsedSource["discovery"]);
        }
        if ("provisioning" in $$parsedSource) {
            $$parsedSource["provisioning"] = $$createField4_0($$parsedSource["provisioning"]);
        }
        return new ControllerSettings($$parsedSource as Partial<ControllerSettings>);
    }
}

export class ControllerSnapshot {
    "settings": ControllerSettings;
    "devices": WLEDDevice[];
    "persistencePath": string;
    "updatedAt": time$0.Time;
    "capabilities": ControllerCapabilities;

    /** Creates a new ControllerSnapshot instance. */
    constructor($$source: Partial<ControllerSnapshot> = {}) {
        if (!("settings" in $$source)) {
            this["settings"] = (new ControllerSettings());
        }
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }
        if (!("persistencePath" in $$source)) {
            this["persistencePath"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = (new ControllerCapabilities());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerSnapshot {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField1_0($$parsedSource["devices"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField4_0($$parsedSource["capabilities"]);
        }
        return new ControllerSnapshot($$parsedSource as Partial<ControllerSnapshot>);
    }
}

export class DiscoverySettings {
    "enabled": boolean;
    "serviceTypes": string[];
    "intervalSeconds": number;
    "queryTimeoutMs": number;

    /** Creates a new DiscoverySettings instance. */
    constructor($$source: Partial<DiscoverySettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("serviceTypes" in $$source)) {
            this["serviceTypes"] = [];
        }
        if (!("intervalSeconds" in $$source)) {
            this["intervalSeconds"] = 0;
        }
        if (!("queryTimeoutMs" in $$source)) {
            this["queryTimeoutMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoverySettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoverySettings {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serviceTypes" in $$parsedSource) {
            $$parsedSource["serviceTypes"] = $$createField1_0($$parsedSource["serviceTypes"]);
        }
        return new DiscoverySettings($$parsedSource as Partial<DiscoverySettings>);
    }
}

export class NetworkApplyResult {
    "dryRun": boolean;
    "warnings"?: string[];
    "steps": NetworkCommandResult[];

    /** Creates a new NetworkApplyResult instance. */
    constructor($$source: Partial<NetworkApplyResult> = {}) {
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkApplyResult {
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField2_0($$parsedSource["steps"]);
        }
        return new NetworkApplyResult($$parsedSource as Partial<NetworkApplyResult>);
    }
}

export class NetworkCommandResult {
    "command": string;
    "output": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new NetworkCommandResult instance. */
    constructor($$source: Partial<NetworkCommandResult> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkCommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkCommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkCommandResult($$parsedSource as Partial<NetworkCommandResult>);
    }
}

export class ProvisioningSettings {
    "autoProvision": boolean;
    "defaultStatePayload": { [_ in string]?: any };
    "defaultConfigPatch": { [_ in string]?: any };

    /** Creates a new ProvisioningSettings instance. */
    constructor($$source: Partial<ProvisioningSettings> = {}) {
        if (!("autoProvision" in $$source)) {
            this["autoProvision"] = false;
        }
        if (!("defaultStatePayload" in $$source)) {
            this["defaultStatePayload"] = {};
        }
        if (!("defaultConfigPatch" in $$source)) {
            this["defaultConfigPatch"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProvisioningSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ProvisioningSettings {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultStatePayload" in $$parsedSource) {
            $$parsedSource["defaultStatePayload"] = $$createField1_0($$parsedSource["defaultStatePayload"]);
        }
        if ("defaultConfigPatch" in $$parsedSource) {
            $$parsedSource["defaultConfigPatch"] = $$createField2_0($$parsedSource["defaultConfigPatch"]);
        }
        return new ProvisioningSettings($$parsedSource as Partial<ProvisioningSettings>);
    }
}

export class UpstreamSettings {
    "autoConnect": boolean;
    "interfaceName": string;
    "ssid": string;
    "password": string;

    /** Creates a new UpstreamSettings instance. */
    constructor($$source: Partial<UpstreamSettings> = {}) {
        if (!("autoConnect" in $$source)) {
            this["autoConnect"] = false;
        }
        if (!("interfaceName" in $$source)) {
            this["interfaceName"] = "";
        }
        if (!("ssid" in $$source)) {
            this["ssid"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpstreamSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UpstreamSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpstreamSettings($$parsedSource as Partial<UpstreamSettings>);
    }
}

export class WLEDDevice {
    "id": string;
    "name": string;
    "host": string;
    "address": string;
    "port": number;
    "lastSeen": time$0.Time;
    "online": boolean;
    "provisioned": boolean;
    "info"?: { [_ in string]?: any };

    /**
     * LastState holds the last known WLED JSON state payload applied to the device (merged over time) for restore on reconnect.
     */
    "lastState"?: { [_ in string]?: any };

    /** Creates a new WLEDDevice instance. */
    constructor($$source: Partial<WLEDDevice> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = null;
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("provisioned" in $$source)) {
            this["provisioned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WLEDDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): WLEDDevice {
        const $$createField8_0 = $$createType12;
        const $$createField9_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField8_0($$parsedSource["info"]);
        }
        if ("lastState" in $$parsedSource) {
            $$parsedSource["lastState"] = $$createField9_0($$parsedSource["lastState"]);
        }
        return new WLEDDevice($$parsedSource as Partial<WLEDDevice>);
    }
}

export class WLEDDeviceDetail {
    "online": boolean;
    "error"?: string;
    "state"?: { [_ in string]?: any };
    "info"?: { [_ in string]?: any };
    "effects"?: string[];
    "palettes"?: string[];
    "config"?: { [_ in string]?: any };
    "lastState"?: { [_ in string]?: any };
    "address": string;
    "port": number;

    /** Creates a new WLEDDeviceDetail instance. */
    constructor($$source: Partial<WLEDDeviceDetail> = {}) {
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WLEDDeviceDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): WLEDDeviceDetail {
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType12;
        const $$createField7_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField3_0($$parsedSource["info"]);
        }
        if ("effects" in $$parsedSource) {
            $$parsedSource["effects"] = $$createField4_0($$parsedSource["effects"]);
        }
        if ("palettes" in $$parsedSource) {
            $$parsedSource["palettes"] = $$createField5_0($$parsedSource["palettes"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField6_0($$parsedSource["config"]);
        }
        if ("lastState" in $$parsedSource) {
            $$parsedSource["lastState"] = $$createField7_0($$parsedSource["lastState"]);
        }
        return new WLEDDeviceDetail($$parsedSource as Partial<WLEDDeviceDetail>);
    }
}

export class WiFiNetwork {
    "ssid": string;
    "signal": number;
    "security": string;

    /** Creates a new WiFiNetwork instance. */
    constructor($$source: Partial<WiFiNetwork> = {}) {
        if (!("ssid" in $$source)) {
            this["ssid"] = "";
        }
        if (!("signal" in $$source)) {
            this["signal"] = 0;
        }
        if (!("security" in $$source)) {
            this["security"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WiFiNetwork instance from a string or object.
     */
    static createFrom($$source: any = {}): WiFiNetwork {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WiFiNetwork($$parsedSource as Partial<WiFiNetwork>);
    }
}

// Private type creation functions
const $$createType0 = AccessPointSettings.createFrom;
const $$createType1 = UpstreamSettings.createFrom;
const $$createType2 = BridgeSettings.createFrom;
const $$createType3 = DiscoverySettings.createFrom;
const $$createType4 = ProvisioningSettings.createFrom;
const $$createType5 = ControllerSettings.createFrom;
const $$createType6 = WLEDDevice.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ControllerCapabilities.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = NetworkCommandResult.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Map($Create.Any, $Create.Any);
