# Gradle Properties
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Versioning
kotlin.version=2.1.0
compose.version=1.7.3
ktor.version=3.0.1
serialization.version=1.7.3
koin.version=4.0.0
jmdns.version=3.5.9
fluentui.version=0.0.1
