// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serial$0 from "../serial/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AccessPointSettings {
    "enabled": boolean;
    "connection": string;
    "interfaceName": string;
    "ssid": string;
    "password": string;
    "channel": number;

    /** Creates a new AccessPointSettings instance. */
    constructor($$source: Partial<AccessPointSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("connection" in $$source)) {
            this["connection"] = "";
        }
        if (!("interfaceName" in $$source)) {
            this["interfaceName"] = "";
        }
        if (!("ssid" in $$source)) {
            this["ssid"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessPointSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessPointSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessPointSettings($$parsedSource as Partial<AccessPointSettings>);
    }
}

export class ArtNetSettings {
    "enabled": boolean;
    "targetHost": string;
    "port": number;
    "net": number;
    "subnet": number;
    "universe": number;
    "refreshHz": number;

    /** Creates a new ArtNetSettings instance. */
    constructor($$source: Partial<ArtNetSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("targetHost" in $$source)) {
            this["targetHost"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("net" in $$source)) {
            this["net"] = 0;
        }
        if (!("subnet" in $$source)) {
            this["subnet"] = 0;
        }
        if (!("universe" in $$source)) {
            this["universe"] = 0;
        }
        if (!("refreshHz" in $$source)) {
            this["refreshHz"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtNetSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ArtNetSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtNetSettings($$parsedSource as Partial<ArtNetSettings>);
    }
}

export class ControllerCapabilities {
    /**
     * NetworkBackendID identifies which integration is active (e.g. "nmcli", "darwin", "netsh", "stub").
     */
    "networkBackendId": string;

    /**
     * NetworkBackendLabel is a human-readable description for the UI.
     */
    "networkBackendLabel": string;

    /**
     * NetworkControlAvailable is true when this OS exposes working CLI tools for applying network settings (partial features may still be unavailable).
     */
    "networkControlAvailable": boolean;

    /**
     * NetworkCliName is the primary host CLI for Wi-Fi on this platform (e.g. nmcli, netsh, networksetup).
     */
    "networkCliName": string;

    /**
     * NetworkCliUnavailableReason is non-empty when NetworkControlAvailable is false; explains which binary or requirement is missing.
     */
    "networkCliUnavailableReason"?: string;

    /**
     * NmcliAvailable is true only when Linux nmcli (NetworkManager) is present and used.
     */
    "nmcliAvailable": boolean;

    /** Creates a new ControllerCapabilities instance. */
    constructor($$source: Partial<ControllerCapabilities> = {}) {
        if (!("networkBackendId" in $$source)) {
            this["networkBackendId"] = "";
        }
        if (!("networkBackendLabel" in $$source)) {
            this["networkBackendLabel"] = "";
        }
        if (!("networkControlAvailable" in $$source)) {
            this["networkControlAvailable"] = false;
        }
        if (!("networkCliName" in $$source)) {
            this["networkCliName"] = "";
        }
        if (!("nmcliAvailable" in $$source)) {
            this["nmcliAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerCapabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ControllerCapabilities($$parsedSource as Partial<ControllerCapabilities>);
    }
}

export class ControllerSettings {
    "accessPoint": AccessPointSettings;
    "wled": WLEDSettings;
    "dmx": DMXSettings;

    /**
     * Legacy flattened settings kept for migration from persisted v2 state.
     */
    "discovery"?: DiscoverySettings;
    "provisioning"?: ProvisioningSettings;
    "testing"?: TestingSettings;

    /** Creates a new ControllerSettings instance. */
    constructor($$source: Partial<ControllerSettings> = {}) {
        if (!("accessPoint" in $$source)) {
            this["accessPoint"] = (new AccessPointSettings());
        }
        if (!("wled" in $$source)) {
            this["wled"] = (new WLEDSettings());
        }
        if (!("dmx" in $$source)) {
            this["dmx"] = (new DMXSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerSettings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accessPoint" in $$parsedSource) {
            $$parsedSource["accessPoint"] = $$createField0_0($$parsedSource["accessPoint"]);
        }
        if ("wled" in $$parsedSource) {
            $$parsedSource["wled"] = $$createField1_0($$parsedSource["wled"]);
        }
        if ("dmx" in $$parsedSource) {
            $$parsedSource["dmx"] = $$createField2_0($$parsedSource["dmx"]);
        }
        if ("discovery" in $$parsedSource) {
            $$parsedSource["discovery"] = $$createField3_0($$parsedSource["discovery"]);
        }
        if ("provisioning" in $$parsedSource) {
            $$parsedSource["provisioning"] = $$createField4_0($$parsedSource["provisioning"]);
        }
        if ("testing" in $$parsedSource) {
            $$parsedSource["testing"] = $$createField5_0($$parsedSource["testing"]);
        }
        return new ControllerSettings($$parsedSource as Partial<ControllerSettings>);
    }
}

export class ControllerSnapshot {
    "settings": ControllerSettings;
    "devices": WLEDDevice[];
    "generalTabState": GeneralTabState;
    "persistencePath": string;
    "updatedAt": time$0.Time;
    "capabilities": ControllerCapabilities;

    /** Creates a new ControllerSnapshot instance. */
    constructor($$source: Partial<ControllerSnapshot> = {}) {
        if (!("settings" in $$source)) {
            this["settings"] = (new ControllerSettings());
        }
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }
        if (!("generalTabState" in $$source)) {
            this["generalTabState"] = (new GeneralTabState());
        }
        if (!("persistencePath" in $$source)) {
            this["persistencePath"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = (new ControllerCapabilities());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerSnapshot {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType9;
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField1_0($$parsedSource["devices"]);
        }
        if ("generalTabState" in $$parsedSource) {
            $$parsedSource["generalTabState"] = $$createField2_0($$parsedSource["generalTabState"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField5_0($$parsedSource["capabilities"]);
        }
        return new ControllerSnapshot($$parsedSource as Partial<ControllerSnapshot>);
    }
}

export class DMXChannel {
    "channel": number;
    "type": string;
    "properties"?: { [_ in string]?: any };

    /** Creates a new DMXChannel instance. */
    constructor($$source: Partial<DMXChannel> = {}) {
        if (!("channel" in $$source)) {
            this["channel"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXChannel instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXChannel {
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField2_0($$parsedSource["properties"]);
        }
        return new DMXChannel($$parsedSource as Partial<DMXChannel>);
    }
}

export class DMXFixture {
    "id": string;
    "type": DMXFixtureType;
    "brand": string;
    "name": string;
    "dmxAddress": number;
    "movingHead": MovingHeadConfig;
    "channels": DMXChannel[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new DMXFixture instance. */
    constructor($$source: Partial<DMXFixture> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = DMXFixtureType.$zero;
        }
        if (!("brand" in $$source)) {
            this["brand"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dmxAddress" in $$source)) {
            this["dmxAddress"] = 0;
        }
        if (!("movingHead" in $$source)) {
            this["movingHead"] = (new MovingHeadConfig());
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXFixture instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXFixture {
        const $$createField5_0 = $$createType12;
        const $$createField6_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("movingHead" in $$parsedSource) {
            $$parsedSource["movingHead"] = $$createField5_0($$parsedSource["movingHead"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField6_0($$parsedSource["channels"]);
        }
        return new DMXFixture($$parsedSource as Partial<DMXFixture>);
    }
}

export enum DMXFixtureType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DMXFixtureTypeMovingHead = "movingHead",
};

export class DMXPartyAudioFeatures {
    "level": number;
    "bass": number;
    "mid": number;
    "treble": number;
    "beat": number;
    "capturedAt": time$0.Time;
    "deviceId"?: string;

    /** Creates a new DMXPartyAudioFeatures instance. */
    constructor($$source: Partial<DMXPartyAudioFeatures> = {}) {
        if (!("level" in $$source)) {
            this["level"] = 0;
        }
        if (!("bass" in $$source)) {
            this["bass"] = 0;
        }
        if (!("mid" in $$source)) {
            this["mid"] = 0;
        }
        if (!("treble" in $$source)) {
            this["treble"] = 0;
        }
        if (!("beat" in $$source)) {
            this["beat"] = 0;
        }
        if (!("capturedAt" in $$source)) {
            this["capturedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXPartyAudioFeatures instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXPartyAudioFeatures {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DMXPartyAudioFeatures($$parsedSource as Partial<DMXPartyAudioFeatures>);
    }
}

export class DMXPartyConfig {
    "enabled": boolean;
    "mode": DMXPartyMode;
    "fixtureIds"?: string[];
    "intensity": number;
    "speed": number;
    "colorVariation": number;
    "audioSensitivity": number;
    "audioInputDeviceId"?: string;

    /** Creates a new DMXPartyConfig instance. */
    constructor($$source: Partial<DMXPartyConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("mode" in $$source)) {
            this["mode"] = DMXPartyMode.$zero;
        }
        if (!("intensity" in $$source)) {
            this["intensity"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("colorVariation" in $$source)) {
            this["colorVariation"] = 0;
        }
        if (!("audioSensitivity" in $$source)) {
            this["audioSensitivity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXPartyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXPartyConfig {
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fixtureIds" in $$parsedSource) {
            $$parsedSource["fixtureIds"] = $$createField2_0($$parsedSource["fixtureIds"]);
        }
        return new DMXPartyConfig($$parsedSource as Partial<DMXPartyConfig>);
    }
}

export enum DMXPartyMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DMXPartyModeAuto = "auto",
    DMXPartyModeAudio = "audio",
};

export class DMXPartyState {
    "config": DMXPartyConfig;
    "status": DMXPartyStatus;
    "audio": DMXPartyAudioFeatures;

    /** Creates a new DMXPartyState instance. */
    constructor($$source: Partial<DMXPartyState> = {}) {
        if (!("config" in $$source)) {
            this["config"] = (new DMXPartyConfig());
        }
        if (!("status" in $$source)) {
            this["status"] = (new DMXPartyStatus());
        }
        if (!("audio" in $$source)) {
            this["audio"] = (new DMXPartyAudioFeatures());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXPartyState instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXPartyState {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType17;
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        if ("audio" in $$parsedSource) {
            $$parsedSource["audio"] = $$createField2_0($$parsedSource["audio"]);
        }
        return new DMXPartyState($$parsedSource as Partial<DMXPartyState>);
    }
}

export class DMXPartyStatus {
    "running": boolean;
    "mode": DMXPartyMode;
    "error"?: string;
    "lastFrameAt"?: time$0.Time;
    "lastAudioAt"?: time$0.Time;
    "audioInputDeviceId"?: string;

    /** Creates a new DMXPartyStatus instance. */
    constructor($$source: Partial<DMXPartyStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("mode" in $$source)) {
            this["mode"] = DMXPartyMode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXPartyStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXPartyStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DMXPartyStatus($$parsedSource as Partial<DMXPartyStatus>);
    }
}

export class DMXSettings {
    "enabled": boolean;
    "usb": USBTransportSettings;
    "artNet": ArtNetSettings;
    "testing": DMXTestingSettings;

    /** Creates a new DMXSettings instance. */
    constructor($$source: Partial<DMXSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("usb" in $$source)) {
            this["usb"] = (new USBTransportSettings());
        }
        if (!("artNet" in $$source)) {
            this["artNet"] = (new ArtNetSettings());
        }
        if (!("testing" in $$source)) {
            this["testing"] = (new DMXTestingSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXSettings {
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType20;
        const $$createField3_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usb" in $$parsedSource) {
            $$parsedSource["usb"] = $$createField1_0($$parsedSource["usb"]);
        }
        if ("artNet" in $$parsedSource) {
            $$parsedSource["artNet"] = $$createField2_0($$parsedSource["artNet"]);
        }
        if ("testing" in $$parsedSource) {
            $$parsedSource["testing"] = $$createField3_0($$parsedSource["testing"]);
        }
        return new DMXSettings($$parsedSource as Partial<DMXSettings>);
    }
}

export class DMXState {
    "fixtures": DMXFixture[];
    "selectedUSBDeviceId": string;
    "party": DMXPartyState;

    /** Creates a new DMXState instance. */
    constructor($$source: Partial<DMXState> = {}) {
        if (!("fixtures" in $$source)) {
            this["fixtures"] = [];
        }
        if (!("selectedUSBDeviceId" in $$source)) {
            this["selectedUSBDeviceId"] = "";
        }
        if (!("party" in $$source)) {
            this["party"] = (new DMXPartyState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXState instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXState {
        const $$createField0_0 = $$createType23;
        const $$createField2_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fixtures" in $$parsedSource) {
            $$parsedSource["fixtures"] = $$createField0_0($$parsedSource["fixtures"]);
        }
        if ("party" in $$parsedSource) {
            $$parsedSource["party"] = $$createField2_0($$parsedSource["party"]);
        }
        return new DMXState($$parsedSource as Partial<DMXState>);
    }
}

export class DMXTestingSettings {
    "simulateUsbDmx": boolean;
    "simulateArtNet": boolean;

    /** Creates a new DMXTestingSettings instance. */
    constructor($$source: Partial<DMXTestingSettings> = {}) {
        if (!("simulateUsbDmx" in $$source)) {
            this["simulateUsbDmx"] = false;
        }
        if (!("simulateArtNet" in $$source)) {
            this["simulateArtNet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DMXTestingSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DMXTestingSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DMXTestingSettings($$parsedSource as Partial<DMXTestingSettings>);
    }
}

export class DiscoverySettings {
    "enabled": boolean;
    "serviceTypes": string[];
    "intervalSeconds": number;
    "queryTimeoutMs": number;
    "bindInterface": string;
    "passiveBrowse": boolean;
    "subnetProbe": boolean;
    "pollIntervalSecondsWhenApEnabled": number;

    /** Creates a new DiscoverySettings instance. */
    constructor($$source: Partial<DiscoverySettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("serviceTypes" in $$source)) {
            this["serviceTypes"] = [];
        }
        if (!("intervalSeconds" in $$source)) {
            this["intervalSeconds"] = 0;
        }
        if (!("queryTimeoutMs" in $$source)) {
            this["queryTimeoutMs"] = 0;
        }
        if (!("bindInterface" in $$source)) {
            this["bindInterface"] = "";
        }
        if (!("passiveBrowse" in $$source)) {
            this["passiveBrowse"] = false;
        }
        if (!("subnetProbe" in $$source)) {
            this["subnetProbe"] = false;
        }
        if (!("pollIntervalSecondsWhenApEnabled" in $$source)) {
            this["pollIntervalSecondsWhenApEnabled"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoverySettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoverySettings {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serviceTypes" in $$parsedSource) {
            $$parsedSource["serviceTypes"] = $$createField1_0($$parsedSource["serviceTypes"]);
        }
        return new DiscoverySettings($$parsedSource as Partial<DiscoverySettings>);
    }
}

export class GeneralTabState {
    "on": boolean;
    "bri": number;
    "rgb": number[];
    "fx": number;
    "pal": number;
    "sx": number;
    "ix": number;

    /** Creates a new GeneralTabState instance. */
    constructor($$source: Partial<GeneralTabState> = {}) {
        if (!("on" in $$source)) {
            this["on"] = false;
        }
        if (!("bri" in $$source)) {
            this["bri"] = 0;
        }
        if (!("rgb" in $$source)) {
            this["rgb"] = Array.from({ length: 3 }, () => 0);
        }
        if (!("fx" in $$source)) {
            this["fx"] = 0;
        }
        if (!("pal" in $$source)) {
            this["pal"] = 0;
        }
        if (!("sx" in $$source)) {
            this["sx"] = 0;
        }
        if (!("ix" in $$source)) {
            this["ix"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralTabState instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneralTabState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneralTabState($$parsedSource as Partial<GeneralTabState>);
    }
}

export class MovingHeadConfig {
    "maxPan": number;
    "maxTilt": number;

    /** Creates a new MovingHeadConfig instance. */
    constructor($$source: Partial<MovingHeadConfig> = {}) {
        if (!("maxPan" in $$source)) {
            this["maxPan"] = 0;
        }
        if (!("maxTilt" in $$source)) {
            this["maxTilt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MovingHeadConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MovingHeadConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MovingHeadConfig($$parsedSource as Partial<MovingHeadConfig>);
    }
}

export class NetworkApplyResult {
    "dryRun": boolean;
    "warnings"?: string[];
    "steps": NetworkCommandResult[];

    /** Creates a new NetworkApplyResult instance. */
    constructor($$source: Partial<NetworkApplyResult> = {}) {
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkApplyResult {
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField2_0($$parsedSource["steps"]);
        }
        return new NetworkApplyResult($$parsedSource as Partial<NetworkApplyResult>);
    }
}

export class NetworkCommandResult {
    "command": string;
    "output": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new NetworkCommandResult instance. */
    constructor($$source: Partial<NetworkCommandResult> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkCommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkCommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkCommandResult($$parsedSource as Partial<NetworkCommandResult>);
    }
}

export class ProvisioningSettings {
    "autoProvision": boolean;
    "defaultStatePayload": { [_ in string]?: any };
    "defaultConfigPatch": { [_ in string]?: any };

    /** Creates a new ProvisioningSettings instance. */
    constructor($$source: Partial<ProvisioningSettings> = {}) {
        if (!("autoProvision" in $$source)) {
            this["autoProvision"] = false;
        }
        if (!("defaultStatePayload" in $$source)) {
            this["defaultStatePayload"] = {};
        }
        if (!("defaultConfigPatch" in $$source)) {
            this["defaultConfigPatch"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProvisioningSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ProvisioningSettings {
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultStatePayload" in $$parsedSource) {
            $$parsedSource["defaultStatePayload"] = $$createField1_0($$parsedSource["defaultStatePayload"]);
        }
        if ("defaultConfigPatch" in $$parsedSource) {
            $$parsedSource["defaultConfigPatch"] = $$createField2_0($$parsedSource["defaultConfigPatch"]);
        }
        return new ProvisioningSettings($$parsedSource as Partial<ProvisioningSettings>);
    }
}

export class TestingSettings {
    "simulateWled": boolean;

    /** Creates a new TestingSettings instance. */
    constructor($$source: Partial<TestingSettings> = {}) {
        if (!("simulateWled" in $$source)) {
            this["simulateWled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestingSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): TestingSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestingSettings($$parsedSource as Partial<TestingSettings>);
    }
}

export const USBSerialDevice = serial$0.USBSerialDevice;
export type USBSerialDevice = serial$0.USBSerialDevice;

export class USBTransportSettings {
    "enabled"?: boolean | null;

    /** Creates a new USBTransportSettings instance. */
    constructor($$source: Partial<USBTransportSettings> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new USBTransportSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): USBTransportSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new USBTransportSettings($$parsedSource as Partial<USBTransportSettings>);
    }
}

export class UpsertDMXFixtureInput {
    "id"?: string;
    "type": DMXFixtureType;
    "brand": string;
    "name": string;
    "dmxAddress": number;
    "maxPan": number;
    "maxTilt": number;
    "channels": DMXChannel[];

    /** Creates a new UpsertDMXFixtureInput instance. */
    constructor($$source: Partial<UpsertDMXFixtureInput> = {}) {
        if (!("type" in $$source)) {
            this["type"] = DMXFixtureType.$zero;
        }
        if (!("brand" in $$source)) {
            this["brand"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dmxAddress" in $$source)) {
            this["dmxAddress"] = 0;
        }
        if (!("maxPan" in $$source)) {
            this["maxPan"] = 0;
        }
        if (!("maxTilt" in $$source)) {
            this["maxTilt"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertDMXFixtureInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertDMXFixtureInput {
        const $$createField7_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField7_0($$parsedSource["channels"]);
        }
        return new UpsertDMXFixtureInput($$parsedSource as Partial<UpsertDMXFixtureInput>);
    }
}

export class WLEDDevice {
    "id": string;
    "name": string;
    "host": string;
    "address": string;
    "port": number;
    "lastSeen": time$0.Time;
    "online": boolean;
    "provisioned": boolean;
    "ignored": boolean;
    "info"?: { [_ in string]?: any };

    /**
     * LastState holds the last known WLED JSON state payload applied to the device (merged over time) for restore on reconnect.
     */
    "lastState"?: { [_ in string]?: any };

    /** Creates a new WLEDDevice instance. */
    constructor($$source: Partial<WLEDDevice> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = null;
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("provisioned" in $$source)) {
            this["provisioned"] = false;
        }
        if (!("ignored" in $$source)) {
            this["ignored"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WLEDDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): WLEDDevice {
        const $$createField9_0 = $$createType11;
        const $$createField10_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField9_0($$parsedSource["info"]);
        }
        if ("lastState" in $$parsedSource) {
            $$parsedSource["lastState"] = $$createField10_0($$parsedSource["lastState"]);
        }
        return new WLEDDevice($$parsedSource as Partial<WLEDDevice>);
    }
}

export class WLEDDeviceDetail {
    "online": boolean;
    "error"?: string;
    "state"?: { [_ in string]?: any };
    "info"?: { [_ in string]?: any };
    "effects"?: string[];
    "palettes"?: string[];
    "config"?: { [_ in string]?: any };
    "lastState"?: { [_ in string]?: any };
    "address": string;
    "port": number;

    /** Creates a new WLEDDeviceDetail instance. */
    constructor($$source: Partial<WLEDDeviceDetail> = {}) {
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WLEDDeviceDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): WLEDDeviceDetail {
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType15;
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField3_0($$parsedSource["info"]);
        }
        if ("effects" in $$parsedSource) {
            $$parsedSource["effects"] = $$createField4_0($$parsedSource["effects"]);
        }
        if ("palettes" in $$parsedSource) {
            $$parsedSource["palettes"] = $$createField5_0($$parsedSource["palettes"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField6_0($$parsedSource["config"]);
        }
        if ("lastState" in $$parsedSource) {
            $$parsedSource["lastState"] = $$createField7_0($$parsedSource["lastState"]);
        }
        return new WLEDDeviceDetail($$parsedSource as Partial<WLEDDeviceDetail>);
    }
}

export class WLEDSettings {
    "enabled": boolean;
    "discovery": DiscoverySettings;
    "provisioning": ProvisioningSettings;
    "testing": TestingSettings;

    /** Creates a new WLEDSettings instance. */
    constructor($$source: Partial<WLEDSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("discovery" in $$source)) {
            this["discovery"] = (new DiscoverySettings());
        }
        if (!("provisioning" in $$source)) {
            this["provisioning"] = (new ProvisioningSettings());
        }
        if (!("testing" in $$source)) {
            this["testing"] = (new TestingSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WLEDSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): WLEDSettings {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("discovery" in $$parsedSource) {
            $$parsedSource["discovery"] = $$createField1_0($$parsedSource["discovery"]);
        }
        if ("provisioning" in $$parsedSource) {
            $$parsedSource["provisioning"] = $$createField2_0($$parsedSource["provisioning"]);
        }
        if ("testing" in $$parsedSource) {
            $$parsedSource["testing"] = $$createField3_0($$parsedSource["testing"]);
        }
        return new WLEDSettings($$parsedSource as Partial<WLEDSettings>);
    }
}

// Private type creation functions
const $$createType0 = AccessPointSettings.createFrom;
const $$createType1 = WLEDSettings.createFrom;
const $$createType2 = DMXSettings.createFrom;
const $$createType3 = DiscoverySettings.createFrom;
const $$createType4 = ProvisioningSettings.createFrom;
const $$createType5 = TestingSettings.createFrom;
const $$createType6 = ControllerSettings.createFrom;
const $$createType7 = WLEDDevice.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = GeneralTabState.createFrom;
const $$createType10 = ControllerCapabilities.createFrom;
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = MovingHeadConfig.createFrom;
const $$createType13 = DMXChannel.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = DMXPartyConfig.createFrom;
const $$createType17 = DMXPartyStatus.createFrom;
const $$createType18 = DMXPartyAudioFeatures.createFrom;
const $$createType19 = USBTransportSettings.createFrom;
const $$createType20 = ArtNetSettings.createFrom;
const $$createType21 = DMXTestingSettings.createFrom;
const $$createType22 = DMXFixture.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = DMXPartyState.createFrom;
const $$createType25 = NetworkCommandResult.createFrom;
const $$createType26 = $Create.Array($$createType25);
