// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dmx$0 from "./internal/dmx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serial$0 from "./internal/serial/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(301739888);
}

export function ApplyDMXLivePatch(updates: dmx$0.DMXOutputUpdate[]): $CancellablePromise<void> {
    return $Call.ByID(503016480, updates);
}

export function ApplyNetworkSettings(): $CancellablePromise<$models.NetworkApplyResult> {
    return $Call.ByID(2142831582).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ControllerSummary(): $CancellablePromise<string> {
    return $Call.ByID(3195005039);
}

export function CreateDMXFixture(input: $models.UpsertDMXFixtureInput): $CancellablePromise<$models.DMXFixture> {
    return $Call.ByID(2468136275, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DefaultControllerSettings(): $CancellablePromise<$models.ControllerSettings> {
    return $Call.ByID(1033104155).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteDMXFixture(id: string): $CancellablePromise<void> {
    return $Call.ByID(303907376, id);
}

export function DiscoverDevicesNow(): $CancellablePromise<$models.WLEDDevice[]> {
    return $Call.ByID(2416920843).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetControllerSnapshot(): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(1398284171).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetDMXLiveStatus(): $CancellablePromise<dmx$0.DMXLiveStatus> {
    return $Call.ByID(3393802248).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetDMXState(): $CancellablePromise<$models.DMXState> {
    return $Call.ByID(108440305).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetDeviceDetail(deviceID: string): $CancellablePromise<$models.WLEDDeviceDetail> {
    return $Call.ByID(2286611580, deviceID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetIgnoredDevices(): $CancellablePromise<$models.WLEDDevice[]> {
    return $Call.ByID(518145222).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(242839354, name);
}

export function ListUSBSerialDevices(): $CancellablePromise<$models.USBSerialDevice[]> {
    return $Call.ByID(660659684).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ProvisionDevice(deviceID: string): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(2603471386, deviceID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RefreshDevice(deviceID: string): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(3772924430, deviceID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RemoveDevice(deviceID: string): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(1916526091, deviceID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RenameDevice(deviceID: string, name: string): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(745484265, deviceID, name).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveControllerSettings(settings: $models.ControllerSettings): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(1996437661, settings).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetDeviceIgnored(deviceID: string, ignored: boolean): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(2049176233, deviceID, ignored).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetDeviceState(deviceID: string, state: { [_ in string]?: any }): $CancellablePromise<$models.ControllerSnapshot> {
    return $Call.ByID(2524256026, deviceID, state).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetGlobalState(state: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2138187373, state).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SetSelectedUSBSerialDevice(deviceID: string): $CancellablePromise<$models.DMXState> {
    return $Call.ByID(354921262, deviceID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function StartDMXLive(fixtureID: string): $CancellablePromise<void> {
    return $Call.ByID(770895038, fixtureID);
}

export function StopDMXLive(): $CancellablePromise<void> {
    return $Call.ByID(3974453572);
}

export function UpdateDMXFixture(input: $models.UpsertDMXFixtureInput): $CancellablePromise<$models.DMXFixture> {
    return $Call.ByID(107365626, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.NetworkApplyResult.createFrom;
const $$createType1 = $models.DMXFixture.createFrom;
const $$createType2 = $models.ControllerSettings.createFrom;
const $$createType3 = $models.WLEDDevice.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ControllerSnapshot.createFrom;
const $$createType6 = dmx$0.DMXLiveStatus.createFrom;
const $$createType7 = $models.DMXState.createFrom;
const $$createType8 = $models.WLEDDeviceDetail.createFrom;
const $$createType9 = serial$0.USBSerialDevice.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
